// Re-exports from all domain modules
export { generateId, toCamel, toSnake } from "./helpers"
export { login, logout, getAuthUser, getSession } from "./auth"
export { getUsers, getUsersByRole, getUser, createUser, updateUser, deleteUser, getSchoolsByUser, getUsersBySchool, addUserSchool, removeUserSchool, replaceUserSchools } from "./users"
export { getSchools, getSchoolsByYear, getSchoolYears, getAcademicYears, getSchool, createSchool, updateSchool, deleteSchool } from "./schools"
export { getClasses, getClassesBySchool, getClass, getClassesBySchoolAndYear, createClass, updateClass, deleteClass } from "./classes"
export { getRooms, getRoomsByClass, getRoom, createRoom, updateRoom, deleteRoom } from "./rooms"
export { getSchedules, getSchedulesByClass, getSchedulesByRoom, createSchedule, updateSchedule, deleteSchedule } from "./schedules"
export { getOrientadorSchedules, getOrientadorSchedulesBySchool, createOrientadorSchedule, updateOrientadorSchedule, deleteOrientadorSchedule, deleteOrientadorSchedulesBySchool } from "./orientador-schedules"
export { getSegmentConfigs, getSegmentConfigsAll, getSegmentConfig, upsertSegmentConfig, deleteSegmentConfig, deleteSegmentConfigsBySchool } from "./segment-configs"
export { getAllItems, getItem, createItem, updateItem, deleteItem } from "./items"
export { getNapItems, getAllNapItems, getNapItemsBySchoolAndYear, getNapItemsBySegment, upsertNapItem, deleteNapItem, deleteNapItemsBySchool, deleteNapItemsBySchoolAndYear } from "./nap-items"
export { getAgendaItems, getAgendaItemsByOrientador, getAgendaItem, createAgendaItem, updateAgendaItem, deleteAgendaItem } from "./agenda"
export { getTbrCategories, getTbrCategory, createTbrCategory, updateTbrCategory, deleteTbrCategory, getAllTbrTeams, getTbrTeamsBySchool, getTbrTeamsByCategory, createTbrTeam, deleteTbrTeam, deleteTbrTeamsBySchool, replaceTbrTeamsForSchool } from "./tbr"
